// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commonservice.proto

package apiservice

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListSubscribedChannelsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSubscribedChannelsRequest) Reset()         { *m = ListSubscribedChannelsRequest{} }
func (m *ListSubscribedChannelsRequest) String() string { return proto.CompactTextString(m) }
func (*ListSubscribedChannelsRequest) ProtoMessage()    {}
func (*ListSubscribedChannelsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74eff72ddf15960, []int{0}
}

func (m *ListSubscribedChannelsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSubscribedChannelsRequest.Unmarshal(m, b)
}
func (m *ListSubscribedChannelsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSubscribedChannelsRequest.Marshal(b, m, deterministic)
}
func (m *ListSubscribedChannelsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSubscribedChannelsRequest.Merge(m, src)
}
func (m *ListSubscribedChannelsRequest) XXX_Size() int {
	return xxx_messageInfo_ListSubscribedChannelsRequest.Size(m)
}
func (m *ListSubscribedChannelsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSubscribedChannelsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSubscribedChannelsRequest proto.InternalMessageInfo

type ListSubscribedChannelsResponse struct {
	Channels             []*Channel `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListSubscribedChannelsResponse) Reset()         { *m = ListSubscribedChannelsResponse{} }
func (m *ListSubscribedChannelsResponse) String() string { return proto.CompactTextString(m) }
func (*ListSubscribedChannelsResponse) ProtoMessage()    {}
func (*ListSubscribedChannelsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74eff72ddf15960, []int{1}
}

func (m *ListSubscribedChannelsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSubscribedChannelsResponse.Unmarshal(m, b)
}
func (m *ListSubscribedChannelsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSubscribedChannelsResponse.Marshal(b, m, deterministic)
}
func (m *ListSubscribedChannelsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSubscribedChannelsResponse.Merge(m, src)
}
func (m *ListSubscribedChannelsResponse) XXX_Size() int {
	return xxx_messageInfo_ListSubscribedChannelsResponse.Size(m)
}
func (m *ListSubscribedChannelsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSubscribedChannelsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSubscribedChannelsResponse proto.InternalMessageInfo

func (m *ListSubscribedChannelsResponse) GetChannels() []*Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type Channel struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Channel) Reset()         { *m = Channel{} }
func (m *Channel) String() string { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()    {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74eff72ddf15960, []int{2}
}

func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (m *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(m, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Channel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ListSubscribedChannelsRequest)(nil), "apiservice.ListSubscribedChannelsRequest")
	proto.RegisterType((*ListSubscribedChannelsResponse)(nil), "apiservice.ListSubscribedChannelsResponse")
	proto.RegisterType((*Channel)(nil), "apiservice.Channel")
}

func init() {
	proto.RegisterFile("commonservice.proto", fileDescriptor_c74eff72ddf15960)
}

var fileDescriptor_c74eff72ddf15960 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0x2b, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x4a, 0x2c, 0xc8, 0x84, 0x8a, 0x48, 0xc9, 0xa4, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x27,
	0x16, 0x64, 0xea, 0x27, 0xe6, 0xe5, 0xe5, 0x97, 0x24, 0x96, 0x64, 0xe6, 0xe7, 0x15, 0x43, 0x54,
	0x2a, 0xc9, 0x73, 0xc9, 0xfa, 0x64, 0x16, 0x97, 0x04, 0x97, 0x26, 0x15, 0x27, 0x17, 0x65, 0x26,
	0xa5, 0xa6, 0x38, 0x67, 0x24, 0xe6, 0xe5, 0xa5, 0xe6, 0x14, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16,
	0x97, 0x28, 0x05, 0x72, 0xc9, 0xe1, 0x52, 0x50, 0x5c, 0x00, 0xb2, 0x57, 0x48, 0x9f, 0x8b, 0x23,
	0x19, 0x2a, 0x26, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0x24, 0xac, 0x87, 0xb0, 0x5f, 0x0f, 0xaa,
	0x3e, 0x08, 0xae, 0x48, 0x49, 0x97, 0x8b, 0x1d, 0x2a, 0x28, 0xc4, 0xc7, 0xc5, 0x94, 0x99, 0x22,
	0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0xc4, 0x94, 0x99, 0x22, 0x24, 0xc4, 0xc5, 0x92, 0x97, 0x98,
	0x9b, 0x2a, 0xc1, 0x04, 0x16, 0x01, 0xb3, 0x8d, 0xa6, 0x31, 0x72, 0xf1, 0x3a, 0x83, 0x3d, 0x19,
	0x0c, 0x31, 0x52, 0xa8, 0x85, 0x91, 0x4b, 0x0c, 0xbb, 0xa3, 0x84, 0x34, 0x91, 0xad, 0xc6, 0xeb,
	0x33, 0x29, 0x2d, 0x62, 0x94, 0x42, 0xfc, 0xa8, 0x24, 0xdc, 0x74, 0xf9, 0xc9, 0x64, 0x26, 0x5e,
	0x21, 0xee, 0x32, 0x43, 0x7d, 0x98, 0x3f, 0x9c, 0x78, 0xa2, 0x90, 0xc2, 0x39, 0x89, 0x0d, 0x1c,
	0xa0, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x78, 0x7f, 0x69, 0x38, 0x91, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CommonServiceClient is the client API for CommonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommonServiceClient interface {
	ListSubscribedChannels(ctx context.Context, in *ListSubscribedChannelsRequest, opts ...grpc.CallOption) (*ListSubscribedChannelsResponse, error)
}

type commonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommonServiceClient(cc grpc.ClientConnInterface) CommonServiceClient {
	return &commonServiceClient{cc}
}

func (c *commonServiceClient) ListSubscribedChannels(ctx context.Context, in *ListSubscribedChannelsRequest, opts ...grpc.CallOption) (*ListSubscribedChannelsResponse, error) {
	out := new(ListSubscribedChannelsResponse)
	err := c.cc.Invoke(ctx, "/apiservice.CommonService/ListSubscribedChannels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommonServiceServer is the server API for CommonService service.
type CommonServiceServer interface {
	ListSubscribedChannels(context.Context, *ListSubscribedChannelsRequest) (*ListSubscribedChannelsResponse, error)
}

// UnimplementedCommonServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCommonServiceServer struct {
}

func (*UnimplementedCommonServiceServer) ListSubscribedChannels(ctx context.Context, req *ListSubscribedChannelsRequest) (*ListSubscribedChannelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSubscribedChannels not implemented")
}

func RegisterCommonServiceServer(s *grpc.Server, srv CommonServiceServer) {
	s.RegisterService(&_CommonService_serviceDesc, srv)
}

func _CommonService_ListSubscribedChannels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubscribedChannelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServiceServer).ListSubscribedChannels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiservice.CommonService/ListSubscribedChannels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServiceServer).ListSubscribedChannels(ctx, req.(*ListSubscribedChannelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CommonService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apiservice.CommonService",
	HandlerType: (*CommonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSubscribedChannels",
			Handler:    _CommonService_ListSubscribedChannels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "commonservice.proto",
}
