// source: bookstore.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
goog.exportSymbol('proto.endpoints.examples.bookstore.Book', null, global);
goog.exportSymbol('proto.endpoints.examples.bookstore.CreateBookRequest', null, global);
goog.exportSymbol('proto.endpoints.examples.bookstore.CreateShelfRequest', null, global);
goog.exportSymbol('proto.endpoints.examples.bookstore.DeleteBookRequest', null, global);
goog.exportSymbol('proto.endpoints.examples.bookstore.DeleteShelfRequest', null, global);
goog.exportSymbol('proto.endpoints.examples.bookstore.GetBookRequest', null, global);
goog.exportSymbol('proto.endpoints.examples.bookstore.GetShelfRequest', null, global);
goog.exportSymbol('proto.endpoints.examples.bookstore.ListBooksRequest', null, global);
goog.exportSymbol('proto.endpoints.examples.bookstore.ListBooksResponse', null, global);
goog.exportSymbol('proto.endpoints.examples.bookstore.ListShelvesResponse', null, global);
goog.exportSymbol('proto.endpoints.examples.bookstore.Shelf', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.endpoints.examples.bookstore.Shelf = function(opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.endpoints.examples.bookstore.Shelf, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.endpoints.examples.bookstore.Shelf.displayName = 'proto.endpoints.examples.bookstore.Shelf';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.endpoints.examples.bookstore.Book = function(opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.endpoints.examples.bookstore.Book, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.endpoints.examples.bookstore.Book.displayName = 'proto.endpoints.examples.bookstore.Book';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.endpoints.examples.bookstore.ListShelvesResponse = function(opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, proto.endpoints.examples.bookstore.ListShelvesResponse.repeatedFields_, null);
};
goog.inherits(proto.endpoints.examples.bookstore.ListShelvesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.endpoints.examples.bookstore.ListShelvesResponse.displayName = 'proto.endpoints.examples.bookstore.ListShelvesResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.endpoints.examples.bookstore.CreateShelfRequest = function(opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.endpoints.examples.bookstore.CreateShelfRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.endpoints.examples.bookstore.CreateShelfRequest.displayName = 'proto.endpoints.examples.bookstore.CreateShelfRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.endpoints.examples.bookstore.GetShelfRequest = function(opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.endpoints.examples.bookstore.GetShelfRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.endpoints.examples.bookstore.GetShelfRequest.displayName = 'proto.endpoints.examples.bookstore.GetShelfRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.endpoints.examples.bookstore.DeleteShelfRequest = function(opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.endpoints.examples.bookstore.DeleteShelfRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.endpoints.examples.bookstore.DeleteShelfRequest.displayName = 'proto.endpoints.examples.bookstore.DeleteShelfRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.endpoints.examples.bookstore.ListBooksRequest = function(opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.endpoints.examples.bookstore.ListBooksRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.endpoints.examples.bookstore.ListBooksRequest.displayName = 'proto.endpoints.examples.bookstore.ListBooksRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.endpoints.examples.bookstore.ListBooksResponse = function(opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, proto.endpoints.examples.bookstore.ListBooksResponse.repeatedFields_, null);
};
goog.inherits(proto.endpoints.examples.bookstore.ListBooksResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.endpoints.examples.bookstore.ListBooksResponse.displayName = 'proto.endpoints.examples.bookstore.ListBooksResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.endpoints.examples.bookstore.CreateBookRequest = function(opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.endpoints.examples.bookstore.CreateBookRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.endpoints.examples.bookstore.CreateBookRequest.displayName = 'proto.endpoints.examples.bookstore.CreateBookRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.endpoints.examples.bookstore.GetBookRequest = function(opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.endpoints.examples.bookstore.GetBookRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.endpoints.examples.bookstore.GetBookRequest.displayName = 'proto.endpoints.examples.bookstore.GetBookRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.endpoints.examples.bookstore.DeleteBookRequest = function(opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.endpoints.examples.bookstore.DeleteBookRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.endpoints.examples.bookstore.DeleteBookRequest.displayName = 'proto.endpoints.examples.bookstore.DeleteBookRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.endpoints.examples.bookstore.Shelf.prototype.toObject = function(opt_includeInstance) {
        return proto.endpoints.examples.bookstore.Shelf.toObject(opt_includeInstance, this);
    };


    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.endpoints.examples.bookstore.Shelf} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.endpoints.examples.bookstore.Shelf.toObject = function(includeInstance, msg) {
        var f, obj = {
            id: jspb.Message.getFieldWithDefault(msg, 1, 0),
            theme: jspb.Message.getFieldWithDefault(msg, 2, "")
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.endpoints.examples.bookstore.Shelf}
 */
proto.endpoints.examples.bookstore.Shelf.deserializeBinary = function(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.endpoints.examples.bookstore.Shelf;
    return proto.endpoints.examples.bookstore.Shelf.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.endpoints.examples.bookstore.Shelf} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.endpoints.examples.bookstore.Shelf}
 */
proto.endpoints.examples.bookstore.Shelf.deserializeBinaryFromReader = function(msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {number} */ (reader.readInt64());
                msg.setId(value);
                break;
            case 2:
                var value = /** @type {string} */ (reader.readString());
                msg.setTheme(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.endpoints.examples.bookstore.Shelf.prototype.serializeBinary = function() {
    var writer = new jspb.BinaryWriter();
    proto.endpoints.examples.bookstore.Shelf.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.endpoints.examples.bookstore.Shelf} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.endpoints.examples.bookstore.Shelf.serializeBinaryToWriter = function(message, writer) {
    var f = undefined;
    f = message.getId();
    if (f !== 0) {
        writer.writeInt64(
            1,
            f
        );
    }
    f = message.getTheme();
    if (f.length > 0) {
        writer.writeString(
            2,
            f
        );
    }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.endpoints.examples.bookstore.Shelf.prototype.getId = function() {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.endpoints.examples.bookstore.Shelf} returns this
 */
proto.endpoints.examples.bookstore.Shelf.prototype.setId = function(value) {
    return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string theme = 2;
 * @return {string}
 */
proto.endpoints.examples.bookstore.Shelf.prototype.getTheme = function() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.endpoints.examples.bookstore.Shelf} returns this
 */
proto.endpoints.examples.bookstore.Shelf.prototype.setTheme = function(value) {
    return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.endpoints.examples.bookstore.Book.prototype.toObject = function(opt_includeInstance) {
        return proto.endpoints.examples.bookstore.Book.toObject(opt_includeInstance, this);
    };


    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.endpoints.examples.bookstore.Book} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.endpoints.examples.bookstore.Book.toObject = function(includeInstance, msg) {
        var f, obj = {
            id: jspb.Message.getFieldWithDefault(msg, 1, 0),
            author: jspb.Message.getFieldWithDefault(msg, 2, ""),
            title: jspb.Message.getFieldWithDefault(msg, 3, "")
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.endpoints.examples.bookstore.Book}
 */
proto.endpoints.examples.bookstore.Book.deserializeBinary = function(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.endpoints.examples.bookstore.Book;
    return proto.endpoints.examples.bookstore.Book.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.endpoints.examples.bookstore.Book} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.endpoints.examples.bookstore.Book}
 */
proto.endpoints.examples.bookstore.Book.deserializeBinaryFromReader = function(msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {number} */ (reader.readInt64());
                msg.setId(value);
                break;
            case 2:
                var value = /** @type {string} */ (reader.readString());
                msg.setAuthor(value);
                break;
            case 3:
                var value = /** @type {string} */ (reader.readString());
                msg.setTitle(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.endpoints.examples.bookstore.Book.prototype.serializeBinary = function() {
    var writer = new jspb.BinaryWriter();
    proto.endpoints.examples.bookstore.Book.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.endpoints.examples.bookstore.Book} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.endpoints.examples.bookstore.Book.serializeBinaryToWriter = function(message, writer) {
    var f = undefined;
    f = message.getId();
    if (f !== 0) {
        writer.writeInt64(
            1,
            f
        );
    }
    f = message.getAuthor();
    if (f.length > 0) {
        writer.writeString(
            2,
            f
        );
    }
    f = message.getTitle();
    if (f.length > 0) {
        writer.writeString(
            3,
            f
        );
    }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.endpoints.examples.bookstore.Book.prototype.getId = function() {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.endpoints.examples.bookstore.Book} returns this
 */
proto.endpoints.examples.bookstore.Book.prototype.setId = function(value) {
    return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string author = 2;
 * @return {string}
 */
proto.endpoints.examples.bookstore.Book.prototype.getAuthor = function() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.endpoints.examples.bookstore.Book} returns this
 */
proto.endpoints.examples.bookstore.Book.prototype.setAuthor = function(value) {
    return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string title = 3;
 * @return {string}
 */
proto.endpoints.examples.bookstore.Book.prototype.getTitle = function() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.endpoints.examples.bookstore.Book} returns this
 */
proto.endpoints.examples.bookstore.Book.prototype.setTitle = function(value) {
    return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.endpoints.examples.bookstore.ListShelvesResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.endpoints.examples.bookstore.ListShelvesResponse.prototype.toObject = function(opt_includeInstance) {
        return proto.endpoints.examples.bookstore.ListShelvesResponse.toObject(opt_includeInstance, this);
    };


    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.endpoints.examples.bookstore.ListShelvesResponse} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.endpoints.examples.bookstore.ListShelvesResponse.toObject = function(includeInstance, msg) {
        var f, obj = {
            shelvesList: jspb.Message.toObjectList(msg.getShelvesList(),
                proto.endpoints.examples.bookstore.Shelf.toObject, includeInstance)
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.endpoints.examples.bookstore.ListShelvesResponse}
 */
proto.endpoints.examples.bookstore.ListShelvesResponse.deserializeBinary = function(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.endpoints.examples.bookstore.ListShelvesResponse;
    return proto.endpoints.examples.bookstore.ListShelvesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.endpoints.examples.bookstore.ListShelvesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.endpoints.examples.bookstore.ListShelvesResponse}
 */
proto.endpoints.examples.bookstore.ListShelvesResponse.deserializeBinaryFromReader = function(msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = new proto.endpoints.examples.bookstore.Shelf;
                reader.readMessage(value, proto.endpoints.examples.bookstore.Shelf.deserializeBinaryFromReader);
                msg.addShelves(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.endpoints.examples.bookstore.ListShelvesResponse.prototype.serializeBinary = function() {
    var writer = new jspb.BinaryWriter();
    proto.endpoints.examples.bookstore.ListShelvesResponse.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.endpoints.examples.bookstore.ListShelvesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.endpoints.examples.bookstore.ListShelvesResponse.serializeBinaryToWriter = function(message, writer) {
    var f = undefined;
    f = message.getShelvesList();
    if (f.length > 0) {
        writer.writeRepeatedMessage(
            1,
            f,
            proto.endpoints.examples.bookstore.Shelf.serializeBinaryToWriter
        );
    }
};


/**
 * repeated Shelf shelves = 1;
 * @return {!Array<!proto.endpoints.examples.bookstore.Shelf>}
 */
proto.endpoints.examples.bookstore.ListShelvesResponse.prototype.getShelvesList = function() {
    return /** @type{!Array<!proto.endpoints.examples.bookstore.Shelf>} */ (
        jspb.Message.getRepeatedWrapperField(this, proto.endpoints.examples.bookstore.Shelf, 1));
};


/**
 * @param {!Array<!proto.endpoints.examples.bookstore.Shelf>} value
 * @return {!proto.endpoints.examples.bookstore.ListShelvesResponse} returns this
 */
proto.endpoints.examples.bookstore.ListShelvesResponse.prototype.setShelvesList = function(value) {
    return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.endpoints.examples.bookstore.Shelf=} opt_value
 * @param {number=} opt_index
 * @return {!proto.endpoints.examples.bookstore.Shelf}
 */
proto.endpoints.examples.bookstore.ListShelvesResponse.prototype.addShelves = function(opt_value, opt_index) {
    return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.endpoints.examples.bookstore.Shelf, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.endpoints.examples.bookstore.ListShelvesResponse} returns this
 */
proto.endpoints.examples.bookstore.ListShelvesResponse.prototype.clearShelvesList = function() {
    return this.setShelvesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.endpoints.examples.bookstore.CreateShelfRequest.prototype.toObject = function(opt_includeInstance) {
        return proto.endpoints.examples.bookstore.CreateShelfRequest.toObject(opt_includeInstance, this);
    };


    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.endpoints.examples.bookstore.CreateShelfRequest} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.endpoints.examples.bookstore.CreateShelfRequest.toObject = function(includeInstance, msg) {
        var f, obj = {
            shelf: (f = msg.getShelf()) && proto.endpoints.examples.bookstore.Shelf.toObject(includeInstance, f)
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.endpoints.examples.bookstore.CreateShelfRequest}
 */
proto.endpoints.examples.bookstore.CreateShelfRequest.deserializeBinary = function(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.endpoints.examples.bookstore.CreateShelfRequest;
    return proto.endpoints.examples.bookstore.CreateShelfRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.endpoints.examples.bookstore.CreateShelfRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.endpoints.examples.bookstore.CreateShelfRequest}
 */
proto.endpoints.examples.bookstore.CreateShelfRequest.deserializeBinaryFromReader = function(msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = new proto.endpoints.examples.bookstore.Shelf;
                reader.readMessage(value, proto.endpoints.examples.bookstore.Shelf.deserializeBinaryFromReader);
                msg.setShelf(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.endpoints.examples.bookstore.CreateShelfRequest.prototype.serializeBinary = function() {
    var writer = new jspb.BinaryWriter();
    proto.endpoints.examples.bookstore.CreateShelfRequest.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.endpoints.examples.bookstore.CreateShelfRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.endpoints.examples.bookstore.CreateShelfRequest.serializeBinaryToWriter = function(message, writer) {
    var f = undefined;
    f = message.getShelf();
    if (f != null) {
        writer.writeMessage(
            1,
            f,
            proto.endpoints.examples.bookstore.Shelf.serializeBinaryToWriter
        );
    }
};


/**
 * optional Shelf shelf = 1;
 * @return {?proto.endpoints.examples.bookstore.Shelf}
 */
proto.endpoints.examples.bookstore.CreateShelfRequest.prototype.getShelf = function() {
    return /** @type{?proto.endpoints.examples.bookstore.Shelf} */ (
        jspb.Message.getWrapperField(this, proto.endpoints.examples.bookstore.Shelf, 1));
};


/**
 * @param {?proto.endpoints.examples.bookstore.Shelf|undefined} value
 * @return {!proto.endpoints.examples.bookstore.CreateShelfRequest} returns this
 */
proto.endpoints.examples.bookstore.CreateShelfRequest.prototype.setShelf = function(value) {
    return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.endpoints.examples.bookstore.CreateShelfRequest} returns this
 */
proto.endpoints.examples.bookstore.CreateShelfRequest.prototype.clearShelf = function() {
    return this.setShelf(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.endpoints.examples.bookstore.CreateShelfRequest.prototype.hasShelf = function() {
    return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.endpoints.examples.bookstore.GetShelfRequest.prototype.toObject = function(opt_includeInstance) {
        return proto.endpoints.examples.bookstore.GetShelfRequest.toObject(opt_includeInstance, this);
    };


    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.endpoints.examples.bookstore.GetShelfRequest} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.endpoints.examples.bookstore.GetShelfRequest.toObject = function(includeInstance, msg) {
        var f, obj = {
            shelf: jspb.Message.getFieldWithDefault(msg, 1, 0)
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.endpoints.examples.bookstore.GetShelfRequest}
 */
proto.endpoints.examples.bookstore.GetShelfRequest.deserializeBinary = function(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.endpoints.examples.bookstore.GetShelfRequest;
    return proto.endpoints.examples.bookstore.GetShelfRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.endpoints.examples.bookstore.GetShelfRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.endpoints.examples.bookstore.GetShelfRequest}
 */
proto.endpoints.examples.bookstore.GetShelfRequest.deserializeBinaryFromReader = function(msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {number} */ (reader.readInt64());
                msg.setShelf(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.endpoints.examples.bookstore.GetShelfRequest.prototype.serializeBinary = function() {
    var writer = new jspb.BinaryWriter();
    proto.endpoints.examples.bookstore.GetShelfRequest.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.endpoints.examples.bookstore.GetShelfRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.endpoints.examples.bookstore.GetShelfRequest.serializeBinaryToWriter = function(message, writer) {
    var f = undefined;
    f = message.getShelf();
    if (f !== 0) {
        writer.writeInt64(
            1,
            f
        );
    }
};


/**
 * optional int64 shelf = 1;
 * @return {number}
 */
proto.endpoints.examples.bookstore.GetShelfRequest.prototype.getShelf = function() {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.endpoints.examples.bookstore.GetShelfRequest} returns this
 */
proto.endpoints.examples.bookstore.GetShelfRequest.prototype.setShelf = function(value) {
    return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.endpoints.examples.bookstore.DeleteShelfRequest.prototype.toObject = function(opt_includeInstance) {
        return proto.endpoints.examples.bookstore.DeleteShelfRequest.toObject(opt_includeInstance, this);
    };


    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.endpoints.examples.bookstore.DeleteShelfRequest} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.endpoints.examples.bookstore.DeleteShelfRequest.toObject = function(includeInstance, msg) {
        var f, obj = {
            shelf: jspb.Message.getFieldWithDefault(msg, 1, 0)
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.endpoints.examples.bookstore.DeleteShelfRequest}
 */
proto.endpoints.examples.bookstore.DeleteShelfRequest.deserializeBinary = function(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.endpoints.examples.bookstore.DeleteShelfRequest;
    return proto.endpoints.examples.bookstore.DeleteShelfRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.endpoints.examples.bookstore.DeleteShelfRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.endpoints.examples.bookstore.DeleteShelfRequest}
 */
proto.endpoints.examples.bookstore.DeleteShelfRequest.deserializeBinaryFromReader = function(msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {number} */ (reader.readInt64());
                msg.setShelf(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.endpoints.examples.bookstore.DeleteShelfRequest.prototype.serializeBinary = function() {
    var writer = new jspb.BinaryWriter();
    proto.endpoints.examples.bookstore.DeleteShelfRequest.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.endpoints.examples.bookstore.DeleteShelfRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.endpoints.examples.bookstore.DeleteShelfRequest.serializeBinaryToWriter = function(message, writer) {
    var f = undefined;
    f = message.getShelf();
    if (f !== 0) {
        writer.writeInt64(
            1,
            f
        );
    }
};


/**
 * optional int64 shelf = 1;
 * @return {number}
 */
proto.endpoints.examples.bookstore.DeleteShelfRequest.prototype.getShelf = function() {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.endpoints.examples.bookstore.DeleteShelfRequest} returns this
 */
proto.endpoints.examples.bookstore.DeleteShelfRequest.prototype.setShelf = function(value) {
    return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.endpoints.examples.bookstore.ListBooksRequest.prototype.toObject = function(opt_includeInstance) {
        return proto.endpoints.examples.bookstore.ListBooksRequest.toObject(opt_includeInstance, this);
    };


    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.endpoints.examples.bookstore.ListBooksRequest} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.endpoints.examples.bookstore.ListBooksRequest.toObject = function(includeInstance, msg) {
        var f, obj = {
            shelf: jspb.Message.getFieldWithDefault(msg, 1, 0)
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.endpoints.examples.bookstore.ListBooksRequest}
 */
proto.endpoints.examples.bookstore.ListBooksRequest.deserializeBinary = function(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.endpoints.examples.bookstore.ListBooksRequest;
    return proto.endpoints.examples.bookstore.ListBooksRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.endpoints.examples.bookstore.ListBooksRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.endpoints.examples.bookstore.ListBooksRequest}
 */
proto.endpoints.examples.bookstore.ListBooksRequest.deserializeBinaryFromReader = function(msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {number} */ (reader.readInt64());
                msg.setShelf(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.endpoints.examples.bookstore.ListBooksRequest.prototype.serializeBinary = function() {
    var writer = new jspb.BinaryWriter();
    proto.endpoints.examples.bookstore.ListBooksRequest.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.endpoints.examples.bookstore.ListBooksRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.endpoints.examples.bookstore.ListBooksRequest.serializeBinaryToWriter = function(message, writer) {
    var f = undefined;
    f = message.getShelf();
    if (f !== 0) {
        writer.writeInt64(
            1,
            f
        );
    }
};


/**
 * optional int64 shelf = 1;
 * @return {number}
 */
proto.endpoints.examples.bookstore.ListBooksRequest.prototype.getShelf = function() {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.endpoints.examples.bookstore.ListBooksRequest} returns this
 */
proto.endpoints.examples.bookstore.ListBooksRequest.prototype.setShelf = function(value) {
    return jspb.Message.setProto3IntField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.endpoints.examples.bookstore.ListBooksResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.endpoints.examples.bookstore.ListBooksResponse.prototype.toObject = function(opt_includeInstance) {
        return proto.endpoints.examples.bookstore.ListBooksResponse.toObject(opt_includeInstance, this);
    };


    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.endpoints.examples.bookstore.ListBooksResponse} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.endpoints.examples.bookstore.ListBooksResponse.toObject = function(includeInstance, msg) {
        var f, obj = {
            booksList: jspb.Message.toObjectList(msg.getBooksList(),
                proto.endpoints.examples.bookstore.Book.toObject, includeInstance)
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.endpoints.examples.bookstore.ListBooksResponse}
 */
proto.endpoints.examples.bookstore.ListBooksResponse.deserializeBinary = function(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.endpoints.examples.bookstore.ListBooksResponse;
    return proto.endpoints.examples.bookstore.ListBooksResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.endpoints.examples.bookstore.ListBooksResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.endpoints.examples.bookstore.ListBooksResponse}
 */
proto.endpoints.examples.bookstore.ListBooksResponse.deserializeBinaryFromReader = function(msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = new proto.endpoints.examples.bookstore.Book;
                reader.readMessage(value, proto.endpoints.examples.bookstore.Book.deserializeBinaryFromReader);
                msg.addBooks(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.endpoints.examples.bookstore.ListBooksResponse.prototype.serializeBinary = function() {
    var writer = new jspb.BinaryWriter();
    proto.endpoints.examples.bookstore.ListBooksResponse.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.endpoints.examples.bookstore.ListBooksResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.endpoints.examples.bookstore.ListBooksResponse.serializeBinaryToWriter = function(message, writer) {
    var f = undefined;
    f = message.getBooksList();
    if (f.length > 0) {
        writer.writeRepeatedMessage(
            1,
            f,
            proto.endpoints.examples.bookstore.Book.serializeBinaryToWriter
        );
    }
};


/**
 * repeated Book books = 1;
 * @return {!Array<!proto.endpoints.examples.bookstore.Book>}
 */
proto.endpoints.examples.bookstore.ListBooksResponse.prototype.getBooksList = function() {
    return /** @type{!Array<!proto.endpoints.examples.bookstore.Book>} */ (
        jspb.Message.getRepeatedWrapperField(this, proto.endpoints.examples.bookstore.Book, 1));
};


/**
 * @param {!Array<!proto.endpoints.examples.bookstore.Book>} value
 * @return {!proto.endpoints.examples.bookstore.ListBooksResponse} returns this
 */
proto.endpoints.examples.bookstore.ListBooksResponse.prototype.setBooksList = function(value) {
    return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.endpoints.examples.bookstore.Book=} opt_value
 * @param {number=} opt_index
 * @return {!proto.endpoints.examples.bookstore.Book}
 */
proto.endpoints.examples.bookstore.ListBooksResponse.prototype.addBooks = function(opt_value, opt_index) {
    return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.endpoints.examples.bookstore.Book, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.endpoints.examples.bookstore.ListBooksResponse} returns this
 */
proto.endpoints.examples.bookstore.ListBooksResponse.prototype.clearBooksList = function() {
    return this.setBooksList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.endpoints.examples.bookstore.CreateBookRequest.prototype.toObject = function(opt_includeInstance) {
        return proto.endpoints.examples.bookstore.CreateBookRequest.toObject(opt_includeInstance, this);
    };


    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.endpoints.examples.bookstore.CreateBookRequest} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.endpoints.examples.bookstore.CreateBookRequest.toObject = function(includeInstance, msg) {
        var f, obj = {
            shelf: jspb.Message.getFieldWithDefault(msg, 1, 0),
            book: (f = msg.getBook()) && proto.endpoints.examples.bookstore.Book.toObject(includeInstance, f)
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.endpoints.examples.bookstore.CreateBookRequest}
 */
proto.endpoints.examples.bookstore.CreateBookRequest.deserializeBinary = function(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.endpoints.examples.bookstore.CreateBookRequest;
    return proto.endpoints.examples.bookstore.CreateBookRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.endpoints.examples.bookstore.CreateBookRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.endpoints.examples.bookstore.CreateBookRequest}
 */
proto.endpoints.examples.bookstore.CreateBookRequest.deserializeBinaryFromReader = function(msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {number} */ (reader.readInt64());
                msg.setShelf(value);
                break;
            case 2:
                var value = new proto.endpoints.examples.bookstore.Book;
                reader.readMessage(value, proto.endpoints.examples.bookstore.Book.deserializeBinaryFromReader);
                msg.setBook(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.endpoints.examples.bookstore.CreateBookRequest.prototype.serializeBinary = function() {
    var writer = new jspb.BinaryWriter();
    proto.endpoints.examples.bookstore.CreateBookRequest.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.endpoints.examples.bookstore.CreateBookRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.endpoints.examples.bookstore.CreateBookRequest.serializeBinaryToWriter = function(message, writer) {
    var f = undefined;
    f = message.getShelf();
    if (f !== 0) {
        writer.writeInt64(
            1,
            f
        );
    }
    f = message.getBook();
    if (f != null) {
        writer.writeMessage(
            2,
            f,
            proto.endpoints.examples.bookstore.Book.serializeBinaryToWriter
        );
    }
};


/**
 * optional int64 shelf = 1;
 * @return {number}
 */
proto.endpoints.examples.bookstore.CreateBookRequest.prototype.getShelf = function() {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.endpoints.examples.bookstore.CreateBookRequest} returns this
 */
proto.endpoints.examples.bookstore.CreateBookRequest.prototype.setShelf = function(value) {
    return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional Book book = 2;
 * @return {?proto.endpoints.examples.bookstore.Book}
 */
proto.endpoints.examples.bookstore.CreateBookRequest.prototype.getBook = function() {
    return /** @type{?proto.endpoints.examples.bookstore.Book} */ (
        jspb.Message.getWrapperField(this, proto.endpoints.examples.bookstore.Book, 2));
};


/**
 * @param {?proto.endpoints.examples.bookstore.Book|undefined} value
 * @return {!proto.endpoints.examples.bookstore.CreateBookRequest} returns this
 */
proto.endpoints.examples.bookstore.CreateBookRequest.prototype.setBook = function(value) {
    return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.endpoints.examples.bookstore.CreateBookRequest} returns this
 */
proto.endpoints.examples.bookstore.CreateBookRequest.prototype.clearBook = function() {
    return this.setBook(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.endpoints.examples.bookstore.CreateBookRequest.prototype.hasBook = function() {
    return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.endpoints.examples.bookstore.GetBookRequest.prototype.toObject = function(opt_includeInstance) {
        return proto.endpoints.examples.bookstore.GetBookRequest.toObject(opt_includeInstance, this);
    };


    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.endpoints.examples.bookstore.GetBookRequest} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.endpoints.examples.bookstore.GetBookRequest.toObject = function(includeInstance, msg) {
        var f, obj = {
            shelf: jspb.Message.getFieldWithDefault(msg, 1, 0),
            book: jspb.Message.getFieldWithDefault(msg, 2, 0)
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.endpoints.examples.bookstore.GetBookRequest}
 */
proto.endpoints.examples.bookstore.GetBookRequest.deserializeBinary = function(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.endpoints.examples.bookstore.GetBookRequest;
    return proto.endpoints.examples.bookstore.GetBookRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.endpoints.examples.bookstore.GetBookRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.endpoints.examples.bookstore.GetBookRequest}
 */
proto.endpoints.examples.bookstore.GetBookRequest.deserializeBinaryFromReader = function(msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {number} */ (reader.readInt64());
                msg.setShelf(value);
                break;
            case 2:
                var value = /** @type {number} */ (reader.readInt64());
                msg.setBook(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.endpoints.examples.bookstore.GetBookRequest.prototype.serializeBinary = function() {
    var writer = new jspb.BinaryWriter();
    proto.endpoints.examples.bookstore.GetBookRequest.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.endpoints.examples.bookstore.GetBookRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.endpoints.examples.bookstore.GetBookRequest.serializeBinaryToWriter = function(message, writer) {
    var f = undefined;
    f = message.getShelf();
    if (f !== 0) {
        writer.writeInt64(
            1,
            f
        );
    }
    f = message.getBook();
    if (f !== 0) {
        writer.writeInt64(
            2,
            f
        );
    }
};


/**
 * optional int64 shelf = 1;
 * @return {number}
 */
proto.endpoints.examples.bookstore.GetBookRequest.prototype.getShelf = function() {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.endpoints.examples.bookstore.GetBookRequest} returns this
 */
proto.endpoints.examples.bookstore.GetBookRequest.prototype.setShelf = function(value) {
    return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 book = 2;
 * @return {number}
 */
proto.endpoints.examples.bookstore.GetBookRequest.prototype.getBook = function() {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.endpoints.examples.bookstore.GetBookRequest} returns this
 */
proto.endpoints.examples.bookstore.GetBookRequest.prototype.setBook = function(value) {
    return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.endpoints.examples.bookstore.DeleteBookRequest.prototype.toObject = function(opt_includeInstance) {
        return proto.endpoints.examples.bookstore.DeleteBookRequest.toObject(opt_includeInstance, this);
    };


    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.endpoints.examples.bookstore.DeleteBookRequest} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.endpoints.examples.bookstore.DeleteBookRequest.toObject = function(includeInstance, msg) {
        var f, obj = {
            shelf: jspb.Message.getFieldWithDefault(msg, 1, 0),
            book: jspb.Message.getFieldWithDefault(msg, 2, 0)
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.endpoints.examples.bookstore.DeleteBookRequest}
 */
proto.endpoints.examples.bookstore.DeleteBookRequest.deserializeBinary = function(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.endpoints.examples.bookstore.DeleteBookRequest;
    return proto.endpoints.examples.bookstore.DeleteBookRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.endpoints.examples.bookstore.DeleteBookRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.endpoints.examples.bookstore.DeleteBookRequest}
 */
proto.endpoints.examples.bookstore.DeleteBookRequest.deserializeBinaryFromReader = function(msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {number} */ (reader.readInt64());
                msg.setShelf(value);
                break;
            case 2:
                var value = /** @type {number} */ (reader.readInt64());
                msg.setBook(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.endpoints.examples.bookstore.DeleteBookRequest.prototype.serializeBinary = function() {
    var writer = new jspb.BinaryWriter();
    proto.endpoints.examples.bookstore.DeleteBookRequest.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.endpoints.examples.bookstore.DeleteBookRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.endpoints.examples.bookstore.DeleteBookRequest.serializeBinaryToWriter = function(message, writer) {
    var f = undefined;
    f = message.getShelf();
    if (f !== 0) {
        writer.writeInt64(
            1,
            f
        );
    }
    f = message.getBook();
    if (f !== 0) {
        writer.writeInt64(
            2,
            f
        );
    }
};


/**
 * optional int64 shelf = 1;
 * @return {number}
 */
proto.endpoints.examples.bookstore.DeleteBookRequest.prototype.getShelf = function() {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.endpoints.examples.bookstore.DeleteBookRequest} returns this
 */
proto.endpoints.examples.bookstore.DeleteBookRequest.prototype.setShelf = function(value) {
    return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 book = 2;
 * @return {number}
 */
proto.endpoints.examples.bookstore.DeleteBookRequest.prototype.getBook = function() {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.endpoints.examples.bookstore.DeleteBookRequest} returns this
 */
proto.endpoints.examples.bookstore.DeleteBookRequest.prototype.setBook = function(value) {
    return jspb.Message.setProto3IntField(this, 2, value);
};


goog.object.extend(exports, proto.endpoints.examples.bookstore);