version: '3'
services:
    server:
        build:
            context: .
        ports:
            - "9090:9090"
        networks:
            envoymesh:
                aliases:
                    - backend-server
    
    envoy:
        # image: envoyproxy/envoy:v1.15.0
        build:
            context: .
            dockerfile: "Dockerfile.proxy"
        # command: envoy -c /etc/envoy.yaml --service-cluster backend-proxy
        # command: envoy -c /etc/envoy/envoy.yaml
        # command: echo hoge
        # volumes:
        #     - ./envoy.yaml:/etc/envoy.yaml
        networks:
            envoymesh:
                aliases:
                    - backend-proxy
        ports:
            - "80:8080"
            - "8881:8881"

networks:
    envoymesh: {}
